WITH all_products AS ( SELECT MODEL,PRICE FROM PC
UNION
SELECT MODEL,PRICE FROM LAPTOP
UNION
SELECT MODEL,PRICE FROM PRINTER)

SELECT MODEL FROM ALL_PRODUCTS

WHERE price = (SELECT MAX(PRICE) FROM ALL_PRODUCTS)
